<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <InvariantGlobalization>true</InvariantGlobalization>
  </PropertyGroup>

  <!-- Внешних пакетов нет: JSON — встроенный System.Text.Json -->
  <ItemGroup>
    <None Update="cities.txt" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
